### ISSUE TITLE
Problem with ubuntu

### ISSUE THREAD

**Issue by MammadTavakoli** [starburstdata/metabase-driver#104]
when i create an docker compose file like this:

```
version: '3'
services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    volumes:
      - data:/metabase
      - ./metabase/plugins:/plugins
volumes:
  data:
```
It work in windows but I can not see straburst in the database list when I run it in ubuntu.
How can I solve this problem?
