### ISSUE TITLE
No fields found for table "XXXX".

### ISSUE THREAD

**Issue by rightx2** [starburstdata/metabase-driver#148]
I've configure trino + metabase environment using docker-compose.
I can connect to trinovia dbeaver and can run sql on my data, perfectly.

But when I try to connect to trino from metabase, I got an error.
Database connection succeded, but when I navigate the table in metabase UI I got an error:

```
No fields found for table "f__trades__entry_exit_info_kis".
```

![Image](https://github.com/user-attachments/assets/6024784f-eefb-4f4a-8ad9-9924266ed2fe)

Below is my configuration information

1. Dockerfile.metabase
```
FROM openjdk:19-buster

ADD https://downloads.metabase.com/v0.52.2.1/metabase.jar /home

CMD ["java", "-jar", "/home/metabase.jar"]
```

2. docker-compose.yml: I only represent the part of the configuration that is relevant to the problem.
```
  metabase:
    build:
      context: .
      dockerfile: Dockerfile.metabase
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      - ./metabase_drivers:/plugins
    ports:
      - 3002:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres-metabase
      MB_PLUGINS_DIR: /plugins
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres-metabase:
    image: postgres:17
    container_name: postgres-metabase
    hostname: postgres-metabase
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-metabase-volume3:/var/lib/postgresql/data
  trino:
    ports:
      - "9090:8443"
    image: "trinodb/trino:445"
    restart: always
    depends_on:
      - ldap
    volumes:
      - ~/dbt-trino/docker/trino/catalog2_from_dbt_demo:/etc/trino/catalog
      - ~/dbt-trino/docker/trino/etc/config.properties:/etc/trino/config.properties:ro
      - ~/dbt-trino/docker/trino/etc/jvm.properties:/etc/trino/jvm.properties:ro
      - ~/dbt-trino/docker/trino/etc/node.properties:/etc/trino/node.properties:ro
      - ~/dbt-trino/docker/trino/etc/password-authenticator.properties:/etc/trino/password-authenticator.properties:ro
      - ./trino_keystore/etc/keystore.jks:/etc/trino/keystore.jks:ro
  ldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "chois"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "XXXXX"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_BASE_DN: "dc=example,dc=com"
      LDAP_TLS: "false"
    ports:
      - "389:389"
    volumes:
      - ./ldap/ldif:/ldif
      - ./ldap/data:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d
```

3. dbeaver connection with trino 
```
jdbc:trino://THIS_IS_MY_HOST.com:9090?SSL=true&SSLVerification=NONE
```

4. starburst driver version used for metabase: 6.1
```
https://github.com/starburstdata/metabase-driver/releases/tag/6.1.0
```

5. metabase database connection info (When I click `save`, it said success)

![Image](https://github.com/user-attachments/assets/78e988ca-f98a-49d5-bb48-af76b88f3287)

with above configs, schema and table are all list up in metabase, but When I click the table, it showed `No fields found for table`  error
